import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

/**
 * Script to add 30 additional rooms to the database.
 * Run with: npx tsx scripts/seed-more-rooms.ts
 */

const ADDITIONAL_ROOMS = [
    // Floor 1 - Standard Rooms
    {
        roomNumber: '103',
        name: 'City View Standard',
        description: 'Comfortable room with city skyline views, modern furnishings, and all essential amenities.',
        bedSize: 'double' as const,
        viewType: 'city' as const,
        basePricePerNight: '180.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'city-view'],
        images: ['/rooms/city-standard-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '104',
        name: 'Pool View Retreat',
        description: 'Relaxing room overlooking the infinity pool with direct pool access.',
        bedSize: 'queen' as const,
        viewType: 'pool' as const,
        basePricePerNight: '250.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'pool-view', 'pool-access'],
        images: ['/rooms/pool-retreat-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '105',
        name: 'Garden Hideaway',
        description: 'Tranquil ground-floor room with private garden terrace and outdoor seating.',
        bedSize: 'king' as const,
        viewType: 'garden' as const,
        basePricePerNight: '280.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'garden-terrace', 'outdoor-seating'],
        images: ['/rooms/garden-hideaway-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '106',
        name: 'Cozy Single',
        description: 'Perfect for solo travelers, featuring a comfortable single bed and workspace.',
        bedSize: 'single' as const,
        viewType: 'city' as const,
        basePricePerNight: '120.00',
        maxOccupancy: 1,
        amenities: ['wifi', 'smart-tv', 'workspace', 'city-view'],
        images: ['/rooms/cozy-single-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '107',
        name: 'Family Garden Suite',
        description: 'Spacious suite with two queen beds, ideal for families with children.',
        bedSize: 'queen' as const,
        viewType: 'garden' as const,
        basePricePerNight: '320.00',
        maxOccupancy: 4,
        amenities: ['wifi', 'smart-tv', 'minibar', 'garden-view', 'extra-beds'],
        images: ['/rooms/family-garden-1.jpg'],
        isAvailable: true,
    },
    // Floor 2 - Deluxe Rooms
    {
        roomNumber: '202',
        name: 'Ocean Horizon Deluxe',
        description: 'Elevated ocean views with premium bedding and enhanced amenities.',
        bedSize: 'king' as const,
        viewType: 'ocean' as const,
        basePricePerNight: '420.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'balcony', 'ocean-view', 'premium-bedding'],
        images: ['/rooms/ocean-horizon-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '203',
        name: 'City Lights Deluxe',
        description: 'Stunning nighttime city views with floor-to-ceiling windows.',
        bedSize: 'king' as const,
        viewType: 'city' as const,
        basePricePerNight: '280.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'panoramic-windows', 'city-view'],
        images: ['/rooms/city-lights-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '204',
        name: 'Poolside Cabana',
        description: 'Direct pool access with private cabana and loungers.',
        bedSize: 'queen' as const,
        viewType: 'pool' as const,
        basePricePerNight: '380.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'pool-access', 'private-cabana', 'sun-loungers'],
        images: ['/rooms/poolside-cabana-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '205',
        name: 'Garden Sanctuary',
        description: 'Zen-inspired room with private garden meditation area.',
        bedSize: 'king' as const,
        viewType: 'garden' as const,
        basePricePerNight: '340.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'garden-view', 'meditation-area', 'yoga-mat'],
        images: ['/rooms/garden-sanctuary-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '206',
        name: 'Couples Retreat',
        description: 'Romantic suite with jacuzzi tub and champagne service.',
        bedSize: 'king' as const,
        viewType: 'ocean' as const,
        basePricePerNight: '480.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'jacuzzi', 'champagne-service', 'ocean-view'],
        images: ['/rooms/couples-retreat-1.jpg'],
        isAvailable: true,
    },
    // Floor 3 - Premium Suites
    {
        roomNumber: '301',
        name: 'Presidential Ocean Suite',
        description: 'Ultimate luxury with two bedrooms, living area, dining room, and butler service.',
        bedSize: 'king' as const,
        viewType: 'ocean' as const,
        basePricePerNight: '1200.00',
        maxOccupancy: 6,
        amenities: ['wifi', 'smart-tv', 'minibar', 'butler-service', 'dining-room', 'living-room', 'ocean-view', 'private-balcony'],
        images: ['/rooms/presidential-suite-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '302',
        name: 'Penthouse Sky Suite',
        description: 'Top-floor penthouse with 360-degree views and private rooftop terrace.',
        bedSize: 'king' as const,
        viewType: 'ocean' as const,
        basePricePerNight: '1500.00',
        maxOccupancy: 4,
        amenities: ['wifi', 'smart-tv', 'minibar', 'rooftop-terrace', 'hot-tub', 'panoramic-view', 'butler-service'],
        images: ['/rooms/penthouse-sky-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '303',
        name: 'Ambassador Suite',
        description: 'Elegant suite with separate office, perfect for business travelers.',
        bedSize: 'king' as const,
        viewType: 'city' as const,
        basePricePerNight: '650.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'private-office', 'meeting-area', 'city-view'],
        images: ['/rooms/ambassador-suite-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '304',
        name: 'Artist Loft',
        description: 'Unique bi-level loft with art gallery and creative workspace.',
        bedSize: 'queen' as const,
        viewType: 'city' as const,
        basePricePerNight: '420.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'loft-design', 'art-collection', 'creative-workspace'],
        images: ['/rooms/artist-loft-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '305',
        name: 'Wellness Retreat',
        description: 'Health-focused suite with in-room sauna and fitness equipment.',
        bedSize: 'king' as const,
        viewType: 'garden' as const,
        basePricePerNight: '520.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'private-sauna', 'fitness-equipment', 'healthy-minibar'],
        images: ['/rooms/wellness-retreat-1.jpg'],
        isAvailable: true,
    },
    // Floor 4 - Specialty Rooms
    {
        roomNumber: '401',
        name: 'Cinema Suite',
        description: 'Entertainment-focused suite with private home theater and gaming setup.',
        bedSize: 'king' as const,
        viewType: 'city' as const,
        basePricePerNight: '580.00',
        maxOccupancy: 4,
        amenities: ['wifi', 'home-theater', 'gaming-console', 'surround-sound', 'popcorn-machine'],
        images: ['/rooms/cinema-suite-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '402',
        name: 'Music Studio Suite',
        description: 'Soundproofed suite with professional-grade music equipment.',
        bedSize: 'queen' as const,
        viewType: 'city' as const,
        basePricePerNight: '450.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'soundproofing', 'music-equipment', 'recording-setup'],
        images: ['/rooms/music-studio-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '403',
        name: 'Chef\'s Kitchen Suite',
        description: 'Gourmet suite with professional kitchen and dining for 8.',
        bedSize: 'king' as const,
        viewType: 'garden' as const,
        basePricePerNight: '620.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'professional-kitchen', 'dining-area', 'wine-fridge'],
        images: ['/rooms/chefs-kitchen-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '404',
        name: 'Library Suite',
        description: 'Quiet retreat with curated book collection and reading nook.',
        bedSize: 'queen' as const,
        viewType: 'garden' as const,
        basePricePerNight: '320.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'book-collection', 'reading-nook', 'fireplace'],
        images: ['/rooms/library-suite-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '405',
        name: 'Tech Haven',
        description: 'Smart suite with voice control, VR setup, and latest gadgets.',
        bedSize: 'king' as const,
        viewType: 'city' as const,
        basePricePerNight: '480.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'voice-control', 'vr-setup', 'smart-home', 'multiple-screens'],
        images: ['/rooms/tech-haven-1.jpg'],
        isAvailable: true,
    },
    // Floor 5 - Family & Group Rooms
    {
        roomNumber: '501',
        name: 'Grand Family Suite',
        description: 'Three-bedroom suite with kids room, living area, and game corner.',
        bedSize: 'king' as const,
        viewType: 'pool' as const,
        basePricePerNight: '780.00',
        maxOccupancy: 8,
        amenities: ['wifi', 'smart-tv', 'minibar', 'kids-room', 'game-corner', 'bunk-beds', 'pool-view'],
        images: ['/rooms/grand-family-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '502',
        name: 'Group Gathering Suite',
        description: 'Perfect for friend groups with multiple beds and entertainment area.',
        bedSize: 'double' as const,
        viewType: 'city' as const,
        basePricePerNight: '520.00',
        maxOccupancy: 6,
        amenities: ['wifi', 'smart-tv', 'minibar', 'multiple-beds', 'entertainment-area', 'city-view'],
        images: ['/rooms/group-gathering-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '503',
        name: 'Pet-Friendly Paradise',
        description: 'Welcoming suite for guests traveling with furry companions.',
        bedSize: 'queen' as const,
        viewType: 'garden' as const,
        basePricePerNight: '290.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'pet-bed', 'pet-bowls', 'garden-access', 'dog-friendly'],
        images: ['/rooms/pet-paradise-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '504',
        name: 'Accessible Ocean Room',
        description: 'Fully accessible room with ocean views and roll-in shower.',
        bedSize: 'king' as const,
        viewType: 'ocean' as const,
        basePricePerNight: '350.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'wheelchair-accessible', 'roll-in-shower', 'grab-bars', 'ocean-view'],
        images: ['/rooms/accessible-ocean-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '505',
        name: 'Extended Stay Studio',
        description: 'Home-like studio with full kitchen, washer/dryer, and workspace.',
        bedSize: 'queen' as const,
        viewType: 'city' as const,
        basePricePerNight: '200.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'full-kitchen', 'washer-dryer', 'workspace', 'city-view'],
        images: ['/rooms/extended-studio-1.jpg'],
        isAvailable: true,
    },
    // Additional Variety
    {
        roomNumber: '601',
        name: 'Sunset Corner Suite',
        description: 'Corner suite with wrap-around windows capturing stunning sunsets.',
        bedSize: 'king' as const,
        viewType: 'ocean' as const,
        basePricePerNight: '450.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'wrap-around-windows', 'sunset-view', 'balcony'],
        images: ['/rooms/sunset-corner-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '602',
        name: 'Minimalist Zen',
        description: 'Clutter-free space with Japanese-inspired design and tatami area.',
        bedSize: 'queen' as const,
        viewType: 'garden' as const,
        basePricePerNight: '300.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'tatami-area', 'shoji-screens', 'zen-garden-view'],
        images: ['/rooms/minimalist-zen-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '603',
        name: 'Vintage Elegance',
        description: 'Classic room with antique furnishings and old-world charm.',
        bedSize: 'queen' as const,
        viewType: 'garden' as const,
        basePricePerNight: '280.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'antique-furniture', 'vintage-decor', 'claw-foot-tub'],
        images: ['/rooms/vintage-elegance-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '604',
        name: 'Tropical Bungalow',
        description: 'Island-inspired room with bamboo accents and tropical plants.',
        bedSize: 'king' as const,
        viewType: 'garden' as const,
        basePricePerNight: '340.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'bamboo-decor', 'tropical-plants', 'outdoor-shower'],
        images: ['/rooms/tropical-bungalow-1.jpg'],
        isAvailable: true,
    },
    {
        roomNumber: '605',
        name: 'Stargazer Suite',
        description: 'Top-floor suite with skylight and telescope for night sky viewing.',
        bedSize: 'king' as const,
        viewType: 'ocean' as const,
        basePricePerNight: '520.00',
        maxOccupancy: 2,
        amenities: ['wifi', 'smart-tv', 'minibar', 'skylight', 'telescope', 'rooftop-access'],
        images: ['/rooms/stargazer-suite-1.jpg'],
        isAvailable: true,
    },
];

async function main() {
    console.log('🌱 Adding 30 additional rooms to database...');

    const { db } = await import('../src/lib/infrastructure/database/drizzle');
    const { rooms } = await import('../src/lib/infrastructure/database/schema');

    try {
        console.log('  📦 Inserting rooms...');
        await db.insert(rooms).values(ADDITIONAL_ROOMS);
        console.log(`  ✓ ${ADDITIONAL_ROOMS.length} rooms added successfully!`);

        console.log('✅ Seeding complete!');
    } catch (error) {
        console.error('❌ Seeding failed:', error);
        throw error;
    }
}

main()
    .catch((error) => {
        console.error(error);
        process.exit(1);
    })
    .finally(() => process.exit(0));
